[package]
name = "tetrix-telnet"
version = "0.1.0"
authors = ["Kevin Mooney <kmooney@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bufstream = "0.1.4"